apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: appka
  name: appka
spec:
  replicas: 4
  selector:
    matchLabels:
      app: appka
  template:
    metadata:
      labels:
        app: appka
        actorSystemName: appka
    spec:
      containers:
      - name: appka
        image: aacevedoosorio/akka-bootstrap:1.0
        imagePullPolicy: Never
        env:
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 19999
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
        # akka-management bootstrap
        - name: bootstrap
          containerPort: 8558
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 19999
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: appka-service
spec:
  # by setting the clusterIp to None we are a "headless service"
  # and thus the svc ("service") DNS record for the single IP but the IPs of all nodes that we select
  #
  # In other words:
  #  $ kubectl exec -it $POD -- nslookup appka-service.default.svc.cluster.local
  #  Server:		10.0.0.10
  #  Address:	10.0.0.10#53
  #
  #  Name:	appka-service.default.svc.cluster.local
  #  Address: 172.17.0.7
  #  Name:	appka-service.default.svc.cluster.local
  #  Address: 172.17.0.8
  #  Name:	appka-service.default.svc.cluster.local
  #  Address: 172.17.0.9
  #  Name:	appka-service.default.svc.cluster.local
  #  Address: 172.17.0.6
  clusterIP: None
  selector:
    app: appka
  ports:
  - protocol: TCP
    port: 8558
    targetPort: 8558